# Generated by Django 3.1.5 on 2021-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricCarList',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('subname', models.CharField(max_length=30, null=True)),
                ('chargetype', models.CharField(max_length=30, null=True)),
                ('onedistance', models.CharField(max_length=30, null=True)),
                ('battery', models.CharField(max_length=30, null=True)),
                ('fastcharge', models.CharField(max_length=30, null=True)),
                ('slowcharge', models.CharField(max_length=30, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
