# Generated by Django 3.1.5 on 2021-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electriccarlist',
            name='battery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='electriccarlist',
            name='onedistance',
            field=models.IntegerField(null=True),
        ),
    ]
